name = "zorvian-platform"
main = "src/worker.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "zorvian-db"
database_id = "90a4c2dc-02e0-49bd-8ae1-525483043bca"
