"""Official Stage 1 source catalog for the Caelomere Knowledge Vault.

Catalog only. No paid databases. No commercial textbook text.
Licences noted for later rights checks; exam-board specs are metadata-only.
"""
from __future__ import annotations

from typing import Any

# Domains permitted for Stage 1 discovery/fetch. Subdomains of these hosts only.
ALLOWLISTED_DOMAINS: frozenset[str] = frozenset(
    {
        "legislation.gov.uk",
        "www.legislation.gov.uk",
        "www.gov.uk",
        "gov.uk",
        "www.hse.gov.uk",
        "hse.gov.uk",
        "www.sra.org.uk",
        "sra.org.uk",
        "www.aqa.org.uk",
        "aqa.org.uk",
        "qualifications.pearson.com",
        "www.ocr.org.uk",
        "ocr.org.uk",
        "www.wjec.co.uk",
        "wjec.co.uk",
        "www.eduqas.co.uk",
        "eduqas.co.uk",
        "www.nationalarchives.gov.uk",
        "nationalarchives.gov.uk",
    }
)

# Hosts whose published specs may be catalogued as metadata but not ingested as body text
# without an explicit licence grant.
METADATA_ONLY_DOMAINS: frozenset[str] = frozenset(
    {
        "www.aqa.org.uk",
        "aqa.org.uk",
        "qualifications.pearson.com",
        "www.ocr.org.uk",
        "ocr.org.uk",
        "www.wjec.co.uk",
        "wjec.co.uk",
        "www.eduqas.co.uk",
        "eduqas.co.uk",
        "www.sra.org.uk",
        "sra.org.uk",
    }
)

# Open Government Licence v3.0 is the default reuse basis for most Crown/GOV.UK/HSE/legislation.gov.uk material.
OGL3 = "OGL-UK-3.0"
CROWN_OGL = "Crown copyright / OGL-UK-3.0 (verify page footer)"
SRA_COPYRIGHT = "SRA copyright — catalog/metadata only unless licence confirmed"
EXAM_BOARD_COPYRIGHT = "Exam-board copyright — public specifications catalogued, body text not ingested in Stage 1"


def _src(**kwargs: Any) -> dict[str, Any]:
    defaults = {
        "active": True,
        "supersedes": None,
        "superseded_by": None,
        "source_version": "catalog-2026-09-03",
        "effective_date": None,
        "published_date": None,
        "machine_readable": False,
        "available_formats": ["HTML"],
        "update_mechanism": "publisher page / collection update — revalidate on next_review",
        "ingestion_method": "allowlisted_fetch_html_normalise",
        "risk_classification": "advisory",
    }
    defaults.update(kwargs)
    return defaults


OFFICIAL_SOURCES: list[dict[str, Any]] = [
    _src(
        source_id="UK_LEGISLATION_PORTAL",
        source_name="legislation.gov.uk",
        authority="The National Archives",
        industry="cross",
        jurisdiction="United Kingdom",
        topic="primary_and_secondary_legislation",
        document_type="legislation_portal",
        legal_status="PRIMARY_LAW",
        source_url="https://www.legislation.gov.uk",
        licence_status=OGL3,
        permitted_use="reproduce under OGL with attribution; not official revised text unless marked",
        attribution="legislation.gov.uk / The National Archives, Open Government Licence v3.0",
        machine_readable=True,
        available_formats=["HTML", "XML", "AKN/XML", "PDF", "RDF"],
        update_mechanism="enactment and revised-version timestamps on each instrument",
        ingestion_method="allowlisted_fetch_html_or_xml",
        risk_classification="high",
    ),
    _src(
        source_id="SRA_STANDARDS_REGULATIONS",
        source_name="SRA Standards and Regulations",
        authority="Solicitors Regulation Authority",
        industry="legal",
        jurisdiction="England and Wales",
        topic="professional_regulation",
        document_type="regulator_handbook",
        legal_status="REGULATOR_RULE",
        source_url="https://www.sra.org.uk/solicitors/standards-regulations/",
        licence_status=SRA_COPYRIGHT,
        permitted_use="link and cite; do not ingest full handbook text without SRA terms review",
        attribution="Solicitors Regulation Authority",
        ingestion_method="metadata_only",
        risk_classification="high",
    ),
    _src(
        source_id="SRA_PRINCIPLES",
        source_name="SRA Principles",
        authority="Solicitors Regulation Authority",
        industry="legal",
        jurisdiction="England and Wales",
        topic="professional_principles",
        document_type="regulator_rule",
        legal_status="REGULATOR_RULE",
        source_url="https://www.sra.org.uk/solicitors/standards-regulations/principles/",
        licence_status=SRA_COPYRIGHT,
        permitted_use="link and cite; metadata only in Stage 1",
        attribution="Solicitors Regulation Authority",
        ingestion_method="metadata_only",
        risk_classification="high",
    ),
    _src(
        source_id="SRA_CODE_SOLICITORS",
        source_name="SRA Code of Conduct for Solicitors, RELs and RFLs",
        authority="Solicitors Regulation Authority",
        industry="legal",
        jurisdiction="England and Wales",
        topic="code_of_conduct",
        document_type="regulator_rule",
        legal_status="REGULATOR_RULE",
        source_url="https://www.sra.org.uk/solicitors/standards-regulations/code-conduct-solicitors/",
        licence_status=SRA_COPYRIGHT,
        permitted_use="link and cite; metadata only in Stage 1",
        attribution="Solicitors Regulation Authority",
        ingestion_method="metadata_only",
        risk_classification="high",
    ),
    _src(
        source_id="SRA_ACCOUNTS_RULES",
        source_name="SRA Accounts Rules",
        authority="Solicitors Regulation Authority",
        industry="legal",
        jurisdiction="England and Wales",
        topic="client_money_accounts",
        document_type="regulator_rule",
        legal_status="REGULATOR_RULE",
        source_url="https://www.sra.org.uk/solicitors/standards-regulations/accounts-rules/",
        licence_status=SRA_COPYRIGHT,
        permitted_use="link and cite; metadata only in Stage 1",
        attribution="Solicitors Regulation Authority",
        ingestion_method="metadata_only",
        risk_classification="high",
    ),
    _src(
        source_id="SRA_GUIDANCE_HUB",
        source_name="SRA Guidance",
        authority="Solicitors Regulation Authority",
        industry="legal",
        jurisdiction="England and Wales",
        topic="regulator_guidance",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.sra.org.uk/solicitors/guidance/",
        licence_status=SRA_COPYRIGHT,
        permitted_use="link and cite; metadata only in Stage 1",
        attribution="Solicitors Regulation Authority",
        ingestion_method="metadata_only",
        risk_classification="high",
    ),
    _src(
        source_id="GOVUK_BUILDING_REGULATIONS",
        source_name="Building Regulations",
        authority="Ministry of Housing, Communities and Local Government / GOV.UK",
        industry="construction",
        jurisdiction="England",
        topic="building_regulations",
        document_type="official_guidance",
        legal_status="STATUTORY_GUIDANCE",
        source_url="https://www.gov.uk/building-regulations",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="GOVUK_APPROVED_DOCUMENTS",
        source_name="Approved Documents (Building Regulations)",
        authority="Ministry of Housing, Communities and Local Government / GOV.UK",
        industry="construction",
        jurisdiction="England",
        topic="approved_documents",
        document_type="statutory_guidance",
        legal_status="STATUTORY_GUIDANCE",
        source_url="https://www.gov.uk/government/collections/approved-documents",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK, Open Government Licence v3.0",
        available_formats=["HTML", "PDF"],
        risk_classification="high",
    ),
    _src(
        source_id="HSE_CONSTRUCTION",
        source_name="HSE Construction",
        authority="Health and Safety Executive",
        industry="construction",
        jurisdiction="Great Britain",
        topic="construction_health_safety",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.hse.gov.uk/construction/",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="Health and Safety Executive, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="HSE_CDM_2015",
        source_name="Construction (Design and Management) Regulations 2015",
        authority="Health and Safety Executive",
        industry="construction",
        jurisdiction="Great Britain",
        topic="cdm_2015",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.hse.gov.uk/construction/cdm/2015/",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="Health and Safety Executive, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="HSE_WORK_AT_HEIGHT",
        source_name="Work at height",
        authority="Health and Safety Executive",
        industry="construction",
        jurisdiction="Great Britain",
        topic="work_at_height",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.hse.gov.uk/work-at-height/",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="Health and Safety Executive, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="HSE_ASBESTOS",
        source_name="Asbestos",
        authority="Health and Safety Executive",
        industry="construction",
        jurisdiction="Great Britain",
        topic="asbestos",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.hse.gov.uk/asbestos/",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="Health and Safety Executive, Open Government Licence v3.0",
        risk_classification="critical",
    ),
    _src(
        source_id="HSE_CONSTRUCTION_DUST",
        source_name="Construction dust",
        authority="Health and Safety Executive",
        industry="construction",
        jurisdiction="Great Britain",
        topic="construction_dust",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.hse.gov.uk/construction/healthrisks/hazardous-substances/construction-dust.htm",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="Health and Safety Executive, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="HSE_PLANT_EQUIPMENT",
        source_name="Work equipment and machinery",
        authority="Health and Safety Executive",
        industry="construction",
        jurisdiction="Great Britain",
        topic="plant_equipment_safety",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.hse.gov.uk/work-equipment-machinery/",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="Health and Safety Executive, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="GOVUK_PRIVATE_RENTING",
        source_name="Private renting",
        authority="GOV.UK",
        industry="property",
        jurisdiction="England",
        topic="private_renting",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.gov.uk/private-renting",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="GOVUK_LANDLORD_RESPONSIBILITIES",
        source_name="Private renting: your rights and responsibilities",
        authority="GOV.UK",
        industry="property",
        jurisdiction="England",
        topic="landlord_safety_responsibilities",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.gov.uk/private-renting/your-landlord-s-safety-responsibilities",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="GOVUK_HMO",
        source_name="House in multiple occupation licence",
        authority="GOV.UK",
        industry="property",
        jurisdiction="England",
        topic="hmo",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.gov.uk/house-in-multiple-occupation-licence",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK, Open Government Licence v3.0",
        risk_classification="high",
    ),
    _src(
        source_id="GOVUK_HHSRS",
        source_name="Housing Health and Safety Rating System guidance",
        authority="GOV.UK / MHCLG",
        industry="property",
        jurisdiction="England",
        topic="hhsrs",
        document_type="official_guidance",
        legal_status="STATUTORY_GUIDANCE",
        source_url="https://www.gov.uk/government/publications/housing-health-and-safety-rating-system-guidance-for-landlords-and-property-related-professionals",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK, Open Government Licence v3.0",
        available_formats=["HTML", "PDF"],
        risk_classification="high",
    ),
    _src(
        source_id="GOVUK_FIRE_SAFETY_ENGLAND",
        source_name="Fire safety: England regulations guidance",
        authority="GOV.UK / Home Office",
        industry="property",
        jurisdiction="England",
        topic="fire_safety",
        document_type="official_guidance",
        legal_status="OFFICIAL_GUIDANCE",
        source_url="https://www.gov.uk/government/collections/fire-safety",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK, Open Government Licence v3.0",
        risk_classification="critical",
    ),
    _src(
        source_id="GOVUK_NATIONAL_CURRICULUM",
        source_name="National Curriculum",
        authority="Department for Education / GOV.UK",
        industry="education",
        jurisdiction="England",
        topic="national_curriculum",
        document_type="curriculum",
        legal_status="CURRICULUM_SPECIFICATION",
        source_url="https://www.gov.uk/national-curriculum",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK / Department for Education, Open Government Licence v3.0",
        risk_classification="medium",
    ),
    _src(
        source_id="GOVUK_NC_COLLECTIONS",
        source_name="National Curriculum collections",
        authority="Department for Education / GOV.UK",
        industry="education",
        jurisdiction="England",
        topic="national_curriculum_documents",
        document_type="curriculum",
        legal_status="CURRICULUM_SPECIFICATION",
        source_url="https://www.gov.uk/government/collections/national-curriculum",
        licence_status=CROWN_OGL,
        permitted_use="reproduce under OGL with attribution after page-level check",
        attribution="GOV.UK / Department for Education, Open Government Licence v3.0",
        available_formats=["HTML", "PDF"],
        risk_classification="medium",
    ),
    _src(
        source_id="AQA_SPECIFICATIONS",
        source_name="AQA specifications",
        authority="AQA",
        industry="education",
        jurisdiction="England",
        topic="exam_specifications",
        document_type="curriculum_specification",
        legal_status="CURRICULUM_SPECIFICATION",
        source_url="https://www.aqa.org.uk/subjects",
        licence_status=EXAM_BOARD_COPYRIGHT,
        permitted_use="catalog and link only; do not ingest specification body text in Stage 1",
        attribution="AQA",
        ingestion_method="metadata_only",
        risk_classification="medium",
    ),
    _src(
        source_id="PEARSON_EDEXCEL_SPECIFICATIONS",
        source_name="Pearson Edexcel specifications",
        authority="Pearson",
        industry="education",
        jurisdiction="England",
        topic="exam_specifications",
        document_type="curriculum_specification",
        legal_status="CURRICULUM_SPECIFICATION",
        source_url="https://qualifications.pearson.com",
        licence_status=EXAM_BOARD_COPYRIGHT,
        permitted_use="catalog and link only; do not ingest specification body text in Stage 1",
        attribution="Pearson",
        ingestion_method="metadata_only",
        risk_classification="medium",
    ),
    _src(
        source_id="OCR_SPECIFICATIONS",
        source_name="OCR specifications",
        authority="OCR (Cambridge OCR)",
        industry="education",
        jurisdiction="England",
        topic="exam_specifications",
        document_type="curriculum_specification",
        legal_status="CURRICULUM_SPECIFICATION",
        source_url="https://www.ocr.org.uk",
        licence_status=EXAM_BOARD_COPYRIGHT,
        permitted_use="catalog and link only; do not ingest specification body text in Stage 1",
        attribution="OCR",
        ingestion_method="metadata_only",
        risk_classification="medium",
    ),
    _src(
        source_id="WJEC_SPECIFICATIONS",
        source_name="WJEC specifications",
        authority="WJEC",
        industry="education",
        jurisdiction="Wales",
        topic="exam_specifications",
        document_type="curriculum_specification",
        legal_status="CURRICULUM_SPECIFICATION",
        source_url="https://www.wjec.co.uk",
        licence_status=EXAM_BOARD_COPYRIGHT,
        permitted_use="catalog and link only; do not ingest specification body text in Stage 1",
        attribution="WJEC",
        ingestion_method="metadata_only",
        risk_classification="medium",
    ),
    _src(
        source_id="EDUQAS_SPECIFICATIONS",
        source_name="Eduqas specifications",
        authority="WJEC Eduqas",
        industry="education",
        jurisdiction="England",
        topic="exam_specifications",
        document_type="curriculum_specification",
        legal_status="CURRICULUM_SPECIFICATION",
        source_url="https://www.eduqas.co.uk",
        licence_status=EXAM_BOARD_COPYRIGHT,
        permitted_use="catalog and link only; do not ingest specification body text in Stage 1",
        attribution="Eduqas / WJEC",
        ingestion_method="metadata_only",
        risk_classification="medium",
    ),
]


INDUSTRY_PACK_SPECS: list[dict[str, Any]] = [
    {
        "pack_id": "CONSTRUCTION_UK",
        "industry": "construction",
        "jurisdiction": "England",
        "name": "Construction (England primary; GB HSE where marked)",
        "version": "1.0.0-stage1",
        "topics": [
            "building_regulations",
            "approved_documents",
            "cdm_2015",
            "work_at_height",
            "asbestos",
            "construction_dust",
            "plant_equipment_safety",
        ],
        "source_ids": [
            "GOVUK_BUILDING_REGULATIONS",
            "GOVUK_APPROVED_DOCUMENTS",
            "HSE_CONSTRUCTION",
            "HSE_CDM_2015",
            "HSE_WORK_AT_HEIGHT",
            "HSE_ASBESTOS",
            "HSE_CONSTRUCTION_DUST",
            "HSE_PLANT_EQUIPMENT",
            "UK_LEGISLATION_PORTAL",
        ],
        "professional_review_rules": [
            "Structural, fire-strategy, CDM dutyholder and asbestos decisions require a qualified professional.",
        ],
        "notes": "HSE pages often apply to Great Britain, not NI. Do not treat as UK-identical.",
    },
    {
        "pack_id": "LEGAL_ENGLAND_WALES",
        "industry": "legal",
        "jurisdiction": "England and Wales",
        "name": "Legal / solicitor regulation (England and Wales)",
        "version": "1.0.0-stage1",
        "topics": [
            "professional_regulation",
            "professional_principles",
            "code_of_conduct",
            "client_money_accounts",
            "primary_and_secondary_legislation",
        ],
        "source_ids": [
            "UK_LEGISLATION_PORTAL",
            "SRA_STANDARDS_REGULATIONS",
            "SRA_PRINCIPLES",
            "SRA_CODE_SOLICITORS",
            "SRA_ACCOUNTS_RULES",
            "SRA_GUIDANCE_HUB",
        ],
        "professional_review_rules": [
            "Any advice that could be relied on as legal advice requires a qualified solicitor or authorised person.",
        ],
        "notes": "SRA regime is England and Wales. Scotland and NI have separate regulators.",
    },
    {
        "pack_id": "PROPERTY_ENGLAND",
        "industry": "property",
        "jurisdiction": "England",
        "name": "Private rented property / landlord (England)",
        "version": "1.0.0-stage1",
        "topics": [
            "private_renting",
            "landlord_safety_responsibilities",
            "hmo",
            "hhsrs",
            "fire_safety",
        ],
        "source_ids": [
            "GOVUK_PRIVATE_RENTING",
            "GOVUK_LANDLORD_RESPONSIBILITIES",
            "GOVUK_HMO",
            "GOVUK_HHSRS",
            "GOVUK_FIRE_SAFETY_ENGLAND",
            "UK_LEGISLATION_PORTAL",
        ],
        "professional_review_rules": [
            "Possession, notice validity, HMO licensing and fire-risk decisions require qualified professional review.",
        ],
        "notes": "Wales, Scotland and NI landlord regimes differ. Pack is England-only.",
    },
    {
        "pack_id": "EDUCATION_UK",
        "industry": "education",
        "jurisdiction": "England",
        "name": "Education specifications and National Curriculum (England; Wales boards catalogued separately)",
        "version": "1.0.0-stage1",
        "topics": [
            "national_curriculum",
            "exam_specifications",
        ],
        "source_ids": [
            "GOVUK_NATIONAL_CURRICULUM",
            "GOVUK_NC_COLLECTIONS",
            "AQA_SPECIFICATIONS",
            "PEARSON_EDEXCEL_SPECIFICATIONS",
            "OCR_SPECIFICATIONS",
            "WJEC_SPECIFICATIONS",
            "EDUQAS_SPECIFICATIONS",
        ],
        "professional_review_rules": [
            "Safeguarding, exam-access arrangements and statutory school decisions require designated safeguarding / qualified staff.",
        ],
        "notes": "National Curriculum pack focus is England. WJEC catalogued for Wales specs; do not collapse nations.",
    },
]

CLIENT_ROUTES: dict[str, str] = {
    "solicitor": "LEGAL_ENGLAND_WALES",
    "lawyer": "LEGAL_ENGLAND_WALES",
    "legal": "LEGAL_ENGLAND_WALES",
    "law_firm": "LEGAL_ENGLAND_WALES",
    "builder": "CONSTRUCTION_UK",
    "contractor": "CONSTRUCTION_UK",
    "construction": "CONSTRUCTION_UK",
    "site_manager": "CONSTRUCTION_UK",
    "landlord": "PROPERTY_ENGLAND",
    "property_manager": "PROPERTY_ENGLAND",
    "letting_agent": "PROPERTY_ENGLAND",
    "property": "PROPERTY_ENGLAND",
    "school": "EDUCATION_UK",
    "tutor": "EDUCATION_UK",
    "teacher": "EDUCATION_UK",
    "education": "EDUCATION_UK",
    "academy": "EDUCATION_UK",
}
