const H={"content-type":"application/json; charset=UTF-8","cache-control":"no-store"};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const uid=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
function text(r){const c=r?.choices?.[0];return String(r?.response||r?.result?.response||r?.output_text||r?.result?.output_text||r?.text||r?.result?.text||c?.message?.content||c?.text||"").trim();}
async function schema(env){if(!env.DB)throw new Error('database_unavailable');await env.DB.prepare(`CREATE TABLE IF NOT EXISTS author_leads(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,book_title TEXT NOT NULL,genre TEXT,vision TEXT,rights_confirmed INTEGER NOT NULL DEFAULT 0,source TEXT NOT NULL DEFAULT 'authors-demo',status TEXT NOT NULL DEFAULT 'new',created_at TEXT NOT NULL)`).run();}
async function demo(request,env){if(!env.AI)return json({error:'ai_unavailable'},503);let b={};try{b=await request.json()}catch{return json({error:'invalid_json'},400)}const q=String(b.question||'').trim().slice(0,1000);if(!q)return json({error:'question_required'},400);const prompt=`You are the Zorvian Living Book demonstration guide. This showcase concerns Lewis Carroll's 1865 public-domain work Alice's Adventures in Wonderland. Answer the visitor's question as an engaging book-club and story-development guide. You may discuss plot, characters, themes and adaptation possibilities. Do not claim access to a copyrighted modern edition, adaptation or illustration. Do not quote long passages. If asked for cinematic development, create an original treatment inspired only by the public-domain story. Keep the answer under 350 words.\n\nVisitor question: ${q}`;try{const r=await env.AI.run('@cf/zai-org/glm-4.7-flash',{messages:[{role:'system',content:'Give a concise, polished reader-facing answer. No internal reasoning.'},{role:'user',content:prompt}],max_tokens:1000,temperature:.55});const a=text(r);return json({ok:true,answer:a||'The AI returned no text.'});}catch(e){return json({error:'ai_request_failed'},502)}}
async function lead(request,env){if(!env.DB)return json({error:'database_unavailable'},503);await schema(env);let b={};try{b=await request.json()}catch{return json({error:'invalid_json'},400)}const name=String(b.name||'').trim().slice(0,120),email=String(b.email||'').trim().toLowerCase().slice(0,254),title=String(b.title||'').trim().slice(0,200);if(!name||!email.includes('@')||!title)return json({error:'name_email_and_book_title_required'},400);if(b.rights!==true)return json({error:'rights_confirmation_required'},400);await env.DB.prepare('INSERT INTO author_leads(id,name,email,book_title,genre,vision,rights_confirmed,source,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(uid(),name,email,title,String(b.genre||'').slice(0,120),String(b.vision||'').slice(0,4000),1,'authors-demo','new',now()).run();return json({ok:true},201)}
export async function handleAuthors(request,env){const u=new URL(request.url),p=u.pathname;if(p==='/api/authors/demo'&&request.method==='POST')return demo(request,env);if(p==='/api/authors/leads'&&request.method==='POST')return lead(request,env);return json({error:'not_found'},404)}
