const H={'content-type':'application/json; charset=UTF-8','cache-control':'no-store'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const now=()=>new Date().toISOString();
function cookie(request,name){const h=request.headers.get('Cookie')||'';const m=h.match(new RegExp(`(?:^|; )${name}=([^;]+)`));return m?m[1]:null;}
async function user(request,env){const sid=cookie(request,'zorvian_session');if(!sid||!env.DB)return null;return env.DB.prepare(`SELECT u.id,u.tenant_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?`).bind(sid,now()).first();}
const tenant=u=>u.tenant_id||'zorvian';
async function schema(env){await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS celestial_media_jobs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,project_id TEXT NOT NULL,kind TEXT NOT NULL,language TEXT NOT NULL,narrator TEXT NOT NULL,status TEXT NOT NULL,provider TEXT,provider_job_id TEXT,output_url TEXT,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_celestial_media_project ON celestial_media_jobs(tenant_id,project_id,updated_at)`)]);}
function config(env){return {configured:Boolean(env.CELESTIAL_RENDER_URL&&env.CELESTIAL_RENDER_TOKEN),render_url_configured:Boolean(env.CELESTIAL_RENDER_URL),render_token_configured:Boolean(env.CELESTIAL_RENDER_TOKEN)};}
async function start(request,env,u){let b={};try{b=await request.json();}catch{return json({error:'invalid_json'},400)}const projectId=String(b.project_id||'').trim(),kind=String(b.kind||'visual').trim(),language=String(b.language||'en-GB').trim(),narrator=String(b.narrator||'storyteller').trim();if(!projectId)return json({error:'project_id_required'},400);const project=await env.DB.prepare('SELECT id,title,visualisation_json FROM author_projects WHERE id=? AND tenant_id=?').bind(projectId,tenant(u)).first();if(!project)return json({error:'project_not_found'},404);if(!config(env).configured)return json({error:'render_provider_not_configured',required_secrets:['CELESTIAL_RENDER_URL','CELESTIAL_RENDER_TOKEN']},503);const id=crypto.randomUUID(),ts=now();await env.DB.prepare('INSERT INTO celestial_media_jobs(id,tenant_id,user_id,project_id,kind,language,narrator,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,tenant(u),u.id,projectId,kind,language,narrator,'queued',ts,ts).run();try{const r=await fetch(env.CELESTIAL_RENDER_URL,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${env.CELESTIAL_RENDER_TOKEN}`},body:JSON.stringify({job_id:id,project_id:projectId,title:project.title,kind,language,narrator,visualisation:JSON.parse(project.visualisation_json)})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`provider_${r.status}`);await env.DB.prepare('UPDATE celestial_media_jobs SET status=?,provider=?,provider_job_id=?,output_url=?,updated_at=? WHERE id=?').bind(data.status||'submitted',data.provider||'celestial-render',data.job_id||null,data.output_url||null,now(),id).run();return json({ok:true,id,status:data.status||'submitted',provider:data.provider||'celestial-render',output_url:data.output_url||null},202)}catch(e){await env.DB.prepare('UPDATE celestial_media_jobs SET status=?,error=?,updated_at=? WHERE id=?').bind('failed',String(e.message||e).slice(0,1000),now(),id).run();return json({error:'render_submission_failed',job_id:id},502)}}
async function jobs(env,u,projectId){const r=await env.DB.prepare('SELECT id,project_id,kind,language,narrator,status,provider,provider_job_id,output_url,error,created_at,updated_at FROM celestial_media_jobs WHERE tenant_id=? AND project_id=? ORDER BY updated_at DESC').bind(tenant(u),projectId).all();return json({ok:true,items:r.results||[]})}
export async function handleCelestialMedia(request,env){if(!env.DB)return json({error:'database_unavailable'},503);await schema(env);const u=await user(request,env);if(!u)return json({error:'unauthorized'},401);const url=new URL(request.url);if(url.pathname==='/api/celestial/status'&&request.method==='GET')return json({ok:true,...config(env),capabilities:['render-job-storage','provider-handoff','language-selection','narrator-selection','output-url-storage']});if(url.pathname==='/api/celestial/render'&&request.method==='POST')return start(request,env,u);if(url.pathname==='/api/celestial/jobs'&&request.method==='GET')return jobs(env,u,url.searchParams.get('project_id')||'');return json({error:'not_found'},404)}