const JSON_HEADERS={"content-type":"application/json; charset=UTF-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
async function sessionUser(request,env){const cookie=request.headers.get("Cookie")||"";const m=cookie.match(/(?:^|; )zorvian_session=([^;]+)/);if(!m||!env.DB)return null;return env.DB.prepare(`SELECT u.id,u.name,u.email,u.role,u.tenant_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?`).bind(m[1],now()).first();}
function serviceUser(request,env){const auth=request.headers.get('Authorization')||'';if(!env.CRM_ADMIN_TOKEN||!auth.startsWith('Bearer '))return null;const token=auth.slice(7).trim();if(!token||token!==env.CRM_ADMIN_TOKEN)return null;return{id:'crm-service',name:'Zorvian CRM Service',email:'service@zorvian.internal',role:'admin',tenant_id:env.CRM_ADMIN_TENANT||'zorvian',service:true};}
async function authenticatedUser(request,env){return serviceUser(request,env)||await sessionUser(request,env);}
async function schema(env){await env.DB.batch([
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_contacts(id TEXT PRIMARY KEY,tenant_id TEXT,name TEXT NOT NULL,email TEXT,phone TEXT,company TEXT,status TEXT NOT NULL DEFAULT 'lead',notes TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_projects(id TEXT PRIMARY KEY,tenant_id TEXT,name TEXT NOT NULL,category TEXT,status TEXT NOT NULL DEFAULT 'active',summary TEXT,next_action TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_tasks(id TEXT PRIMARY KEY,tenant_id TEXT,project_id TEXT,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',priority TEXT NOT NULL DEFAULT 'normal',due_at TEXT,notes TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_activity(id TEXT PRIMARY KEY,tenant_id TEXT,entity_type TEXT,entity_id TEXT,action TEXT NOT NULL,detail TEXT,created_at TEXT NOT NULL)`),
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_agent_runs(id TEXT PRIMARY KEY,tenant_id TEXT,task_id TEXT,instruction TEXT NOT NULL,result TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL)`)
]);}
const tenant=u=>u.tenant_id||'zorvian';
async function list(env,u,type){const t=tenant(u);if(type==='contacts')return env.DB.prepare('SELECT * FROM crm_contacts WHERE tenant_id=? ORDER BY updated_at DESC').bind(t).all();if(type==='projects')return env.DB.prepare('SELECT * FROM crm_projects WHERE tenant_id=? ORDER BY updated_at DESC').bind(t).all();if(type==='tasks')return env.DB.prepare('SELECT * FROM crm_tasks WHERE tenant_id=? ORDER BY CASE status WHEN \'open\' THEN 0 ELSE 1 END, updated_at DESC').bind(t).all();if(type==='activity')return env.DB.prepare('SELECT * FROM crm_activity WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100').bind(t).all();if(type==='agent-runs')return env.DB.prepare('SELECT * FROM crm_agent_runs WHERE tenant_id=? ORDER BY created_at DESC LIMIT 50').bind(t).all();return null;}
async function create(env,u,type,b){const id=uid(),ts=now(),t=tenant(u);if(type==='contacts'){await env.DB.prepare('INSERT INTO crm_contacts(id,tenant_id,name,email,phone,company,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,t,String(b.name||'').trim(),b.email||'',b.phone||'',b.company||'',b.status||'lead',b.notes||'',ts,ts).run();}else if(type==='projects'){await env.DB.prepare('INSERT INTO crm_projects(id,tenant_id,name,category,status,summary,next_action,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,t,String(b.name||'').trim(),b.category||'',b.status||'active',b.summary||'',b.next_action||'',ts,ts).run();}else if(type==='tasks'){await env.DB.prepare('INSERT INTO crm_tasks(id,tenant_id,project_id,title,status,priority,due_at,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,t,b.project_id||'',String(b.title||'').trim(),b.status||'open',b.priority||'normal',b.due_at||null,b.notes||'',ts,ts).run();}else return null;await env.DB.prepare('INSERT INTO crm_activity(id,tenant_id,entity_type,entity_id,action,detail,created_at) VALUES(?,?,?,?,?,?,?)').bind(uid(),t,type,id,'created',String(b.name||b.title||''),ts).run();return{id};}
async function runAgent(env,u,b){if(!env.AI)return json({error:'ai_unavailable'},503);const t=tenant(u);let instruction=String(b.instruction||'').trim(),task=null;if(b.task_id){task=await env.DB.prepare('SELECT * FROM crm_tasks WHERE id=? AND tenant_id=?').bind(b.task_id,t).first();if(!task)return json({error:'task_not_found'},404);instruction=instruction||`Complete this CRM task and return the finished deliverable:\nTask: ${task.title}\nNotes: ${task.notes||''}`;}if(!instruction)return json({error:'instruction_required'},400);const projects=await env.DB.prepare('SELECT name,category,status,summary,next_action FROM crm_projects WHERE tenant_id=? ORDER BY updated_at DESC LIMIT 20').bind(t).all();const prompt=`You are the Zorvian CRM AI Agent. Complete business tasks, create polished deliverables, and use the CRM project context. Do not claim external actions were completed unless the instruction only requires content or analysis.\n\nPROJECT CONTEXT:\n${JSON.stringify(projects.results||[])}\n\nINSTRUCTION:\n${instruction}`;let out;try{out=await env.AI.run('@cf/meta/llama-3.1-8b-instruct',{messages:[{role:'system',content:'You are a practical business operations agent inside Zorvian CRM. Produce the finished work, not just advice.'},{role:'user',content:prompt}]});}catch(e){return json({error:'agent_failed',detail:String(e?.message||e)},500);}const result=String(out?.response||out?.result?.response||out?.text||'').trim();if(!result)return json({error:'empty_agent_result'},500);const runId=uid(),ts=now();await env.DB.prepare('INSERT INTO crm_agent_runs(id,tenant_id,task_id,instruction,result,status,created_at) VALUES(?,?,?,?,?,?,?)').bind(runId,t,task?.id||null,instruction,result,'completed',ts).run();if(task){const notes=[task.notes||'',`\n\n--- AI AGENT RESULT ${ts} ---\n${result}`].join('');await env.DB.prepare('UPDATE crm_tasks SET notes=?,status=?,updated_at=? WHERE id=? AND tenant_id=?').bind(notes,'done',ts,task.id,t).run();}await env.DB.prepare('INSERT INTO crm_activity(id,tenant_id,entity_type,entity_id,action,detail,created_at) VALUES(?,?,?,?,?,?,?)').bind(uid(),t,'agent',runId,'completed',task?task.title:instruction.slice(0,120),ts).run();return json({ok:true,run_id:runId,result,task_completed:Boolean(task)});}
export async function handleCRM(request,env){if(!env.DB)return json({error:'database_unavailable'},503);const u=await authenticatedUser(request,env);if(!u)return json({error:'unauthorized'},401);await schema(env);const url=new URL(request.url),parts=url.pathname.split('/').filter(Boolean),type=parts[2],id=parts[3];if(type==='status'&&request.method==='GET')return json({ok:true,service:Boolean(u.service),tenant:tenant(u),agent:Boolean(env.AI),capabilities:['contacts','projects','tasks','activity','agent-run','agent-runs']});if(type==='agent'&&id==='run'&&request.method==='POST'){let b={};try{b=await request.json()}catch{return json({error:'invalid_json'},400)};return runAgent(env,u,b);}if(request.method==='GET'&&!id){const r=await list(env,u,type);return r?json({ok:true,items:r.results||[]}):json({error:'not_found'},404);}if(request.method==='POST'&&!id){let b={};try{b=await request.json()}catch{return json({error:'invalid_json'},400)};if(!(b.name||b.title))return json({error:'name_or_title_required'},400);const r=await create(env,u,type,b);return r?json({ok:true,...r},201):json({error:'not_found'},404);}if(request.method==='PATCH'&&id){let b={};try{b=await request.json()}catch{return json({error:'invalid_json'},400)};const allowed={contacts:['name','email','phone','company','status','notes'],projects:['name','category','status','summary','next_action'],tasks:['project_id','title','status','priority','due_at','notes']}[type];if(!allowed)return json({error:'not_found'},404);const keys=allowed.filter(k=>Object.prototype.hasOwnProperty.call(b,k));if(!keys.length)return json({error:'nothing_to_update'},400);const table='crm_'+type,sql=`UPDATE ${table} SET ${keys.map(k=>k+'=?').join(',')},updated_at=? WHERE id=? AND tenant_id=?`;await env.DB.prepare(sql).bind(...keys.map(k=>b[k]),now(),id,tenant(u)).run();await env.DB.prepare('INSERT INTO crm_activity(id,tenant_id,entity_type,entity_id,action,detail,created_at) VALUES(?,?,?,?,?,?,?)').bind(uid(),tenant(u),type,id,'updated',keys.join(', '),now()).run();return json({ok:true});}return json({error:'not_found'},404);}
