const JSON_HEADERS={"content-type":"application/json; charset=UTF-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
async function user(request,env){const cookie=request.headers.get("Cookie")||"";const m=cookie.match(/(?:^|; )zorvian_session=([^;]+)/);if(!m||!env.DB)return null;return env.DB.prepare(`SELECT u.id,u.name,u.email,u.role,u.tenant_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?`).bind(m[1],now()).first();}
async function schema(env){await env.DB.batch([
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_contacts(id TEXT PRIMARY KEY,tenant_id TEXT,name TEXT NOT NULL,email TEXT,phone TEXT,company TEXT,status TEXT NOT NULL DEFAULT 'lead',notes TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_projects(id TEXT PRIMARY KEY,tenant_id TEXT,name TEXT NOT NULL,category TEXT,status TEXT NOT NULL DEFAULT 'active',summary TEXT,next_action TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_tasks(id TEXT PRIMARY KEY,tenant_id TEXT,project_id TEXT,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',priority TEXT NOT NULL DEFAULT 'normal',due_at TEXT,notes TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_activity(id TEXT PRIMARY KEY,tenant_id TEXT,entity_type TEXT,entity_id TEXT,action TEXT NOT NULL,detail TEXT,created_at TEXT NOT NULL)`)
]);}
const tenant=u=>u.tenant_id||'zorvian';
async function list(env,u,type){const t=tenant(u);if(type==='contacts')return env.DB.prepare('SELECT * FROM crm_contacts WHERE tenant_id=? ORDER BY updated_at DESC').bind(t).all();if(type==='projects')return env.DB.prepare('SELECT * FROM crm_projects WHERE tenant_id=? ORDER BY updated_at DESC').bind(t).all();if(type==='tasks')return env.DB.prepare('SELECT * FROM crm_tasks WHERE tenant_id=? ORDER BY CASE status WHEN \'open\' THEN 0 ELSE 1 END, updated_at DESC').bind(t).all();if(type==='activity')return env.DB.prepare('SELECT * FROM crm_activity WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100').bind(t).all();return null;}
async function create(env,u,type,b){const id=uid(),ts=now(),t=tenant(u);if(type==='contacts'){await env.DB.prepare('INSERT INTO crm_contacts(id,tenant_id,name,email,phone,company,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,t,String(b.name||'').trim(),b.email||'',b.phone||'',b.company||'',b.status||'lead',b.notes||'',ts,ts).run();}else if(type==='projects'){await env.DB.prepare('INSERT INTO crm_projects(id,tenant_id,name,category,status,summary,next_action,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,t,String(b.name||'').trim(),b.category||'',b.status||'active',b.summary||'',b.next_action||'',ts,ts).run();}else if(type==='tasks'){await env.DB.prepare('INSERT INTO crm_tasks(id,tenant_id,project_id,title,status,priority,due_at,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,t,b.project_id||'',String(b.title||'').trim(),b.status||'open',b.priority||'normal',b.due_at||null,b.notes||'',ts,ts).run();}else return null;await env.DB.prepare('INSERT INTO crm_activity(id,tenant_id,entity_type,entity_id,action,detail,created_at) VALUES(?,?,?,?,?,?,?)').bind(uid(),t,type,id,'created',String(b.name||b.title||''),ts).run();return{id};}
export async function handleCRM(request,env){if(!env.DB)return json({error:'database_unavailable'},503);const u=await user(request,env);if(!u)return json({error:'unauthorized'},401);await schema(env);const url=new URL(request.url),parts=url.pathname.split('/').filter(Boolean),type=parts[2],id=parts[3];if(request.method==='GET'&&!id){const r=await list(env,u,type);return r?json({ok:true,items:r.results||[]}):json({error:'not_found'},404);}if(request.method==='POST'&&!id){let b={};try{b=await request.json()}catch{return json({error:'invalid_json'},400)};if(!(b.name||b.title))return json({error:'name_or_title_required'},400);const r=await create(env,u,type,b);return r?json({ok:true,...r},201):json({error:'not_found'},404);}if(request.method==='PATCH'&&id){let b={};try{b=await request.json()}catch{return json({error:'invalid_json'},400)};const allowed={contacts:['name','email','phone','company','status','notes'],projects:['name','category','status','summary','next_action'],tasks:['project_id','title','status','priority','due_at','notes']}[type];if(!allowed)return json({error:'not_found'},404);const keys=allowed.filter(k=>Object.prototype.hasOwnProperty.call(b,k));if(!keys.length)return json({error:'nothing_to_update'},400);const table='crm_'+type,sql=`UPDATE ${table} SET ${keys.map(k=>k+'=?').join(',')},updated_at=? WHERE id=? AND tenant_id=?`;await env.DB.prepare(sql).bind(...keys.map(k=>b[k]),now(),id,tenant(u)).run();return json({ok:true});}return json({error:'not_found'},404);}
