import legacyWorker from "./worker.js";

const AI_MODEL = "@cf/zai-org/glm-4.7-flash";
const JSON_HEADERS = { "content-type": "application/json; charset=UTF-8", "cache-control": "no-store" };
const TOOL_PROMPTS = {
  receptionist: "You are Zorvian AI Receptionist.",
  calendar: "You are Zorvian AI Calendar Assistant.",
  booking: "You are Zorvian AI Booking Assistant.",
  leads: "You are Zorvian AI Lead Intelligence Assistant.",
  social: "You are Zorvian AI Social Assistant.",
  marketing: "You are Zorvian AI Marketing Assistant.",
  support: "You are Zorvian AI Customer Support Assistant.",
  quotes: "You are Zorvian AI Sales and Quotes Assistant.",
  tasks: "You are Zorvian AI Task Assistant.",
  intelligence: "You are Zorvian Business Intelligence Assistant.",
  command: "You are Zorvian business control AI.",
  ask: "You are Zorvian, a concise business AI assistant."
};

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});}
function getCookie(request,name){const h=request.headers.get("Cookie")||"";const m=h.match(new RegExp(`(?:^|; )${name}=([^;]+)`));return m?m[1]:null;}
async function getUser(request,env){const id=getCookie(request,"zorvian_session");if(!id||!env.DB)return null;return env.DB.prepare(`SELECT s.id,s.expires_at,u.id AS user_id,u.name,u.email,u.role,u.tenant_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?`).bind(id,new Date().toISOString()).first();}
function firstMatch(pattern,text){const m=text.match(pattern);return m?m[1].trim():"";}
function extractReply(result){const c=result?.choices?.[0];return String(result?.response||result?.result?.response||result?.output_text||result?.result?.output_text||result?.text||result?.result?.text||c?.message?.content||c?.text||"").trim();}
const INTERNAL_MARKERS=/(?:system prompt|system message|developer message|internal instructions|hidden instructions|chain[- ]of[- ]thought|drafting notes|the user wants an output|the output should follow|content_type\s*=|\[instruction\]|```(?:json|text)?)/i;
const DURATION_QUANTITY="(?:\\d+(?:\\.\\d+)?|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|a|an)";
const DURATION_UNIT="(?:day|days|week|weeks|hour|hours)";

function extractReceptionistFacts(message){
  const text=String(message||"").replace(/\s+/g," ").trim();
  const name=firstMatch(/(?:my name is|i am|i['’]m)\s+([A-Z][A-Za-z' -]{1,60}?)(?:\.|,|\s+i\b|\s+from\b|\s+and\b|\s+i run\b)/i,text);
  const phone=firstMatch(/(?:phone(?: number)?|mobile|number|contact me at)\s*(?:is|:)?\s*((?:\+44\s?\d|0\d)[\d\s-]{8,16})/i,text).replace(/[\s-]+/g,"");
  const duration=firstMatch(new RegExp(`\\b(?:for|lasting)\\s+(${DURATION_QUANTITY}\\s*${DURATION_UNIT})\\b`,"i"),text);
  const exactStart=firstMatch(/\b(?:starting|start(?:ing)?|from)\s+((?:(?:next|this)\s+)?(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)|today|tomorrow|\d{1,2}(?:st|nd|rd|th)?\s+[A-Za-z]+(?:\s+\d{4})?)/i,text);
  const broadTiming=firstMatch(/\b((?:next|this)\s+(?:week|month))\b/i,text);const start=exactStart||broadTiming;
  const rawLocation=firstMatch(/\b(?:in|near)\s+([A-Z][A-Za-z -]{2,40})(?=\.|,|\s+i\b|\s+we\b|\s+and\b|\s+for\b|$)/,text);
  const location=rawLocation.replace(/\s+(?:next|this)\s+(?:week|month)$/i,"").trim();
  const companyFrom=firstMatch(/(?:my name is|i am|i['’]m)\s+[A-Z][A-Za-z' -]{1,60}?\s+from\s+(.+?)(?=\s+in\s+[A-Z]|\.\s+i\b|\.\s+we\b|\s+and\s+(?:i|we)\b|$)/i,text);
  const companyDirect=firstMatch(/(?:i run|i own|i work for)\s+(?:a\s+)?(.+?)(?=\s+in\s+[A-Z]|\.\s+i\b|\.\s+we\b|$)/i,text);const company=companyFrom||companyDirect;
  let service=firstMatch(new RegExp(`(?:need to|want to|looking to)\\s+(?:hire|rent|book|buy|arrange|order)\\s+(.+?)(?=\\s+for\\s+${DURATION_QUANTITY}\\s*${DURATION_UNIT}\\b|\\s+starting\\b|\\s+from\\b|\\s+on\\b|\\.|$)`,"i"),text);service=service.replace(/\s+for\s+(?:a|an|the)?\s*job\b.*$/i,"").trim();
  const email=firstMatch(/\b([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})\b/i,text);
  return {text,name,phone,duration,start,location,company,service,email,broadTiming:Boolean(broadTiming&&!exactStart),availabilityRequested:/\bavailable\b|\bavailability\b|\bin stock\b|\bfree\b/i.test(text),urgent:/\burgent\b|\basap\b|\bimmediately\b|\bemergency\b/i.test(text)};
}
function receptionistResponse(message){const f=extractReceptionistFacts(message),missing=[];if(!f.start)missing.push("confirmed start date/time");else if(f.broadTiming)missing.push("exact start date/time");if(!f.duration)missing.push("hire duration");if(!f.phone&&!f.email)missing.push("phone number or email address");if(!f.location)missing.push("exact job or delivery location");return ["Customer need",[f.service,f.duration?`for ${f.duration}`:""].filter(Boolean).join(" ")||"Customer requirement is contained in the original enquiry.","","Details already provided",f.name?`Customer: ${f.name}`:"Customer name: not clearly provided.",f.company?`Business: ${f.company}`:"Business: not clearly provided.",f.location?`Location: ${f.location}`:"Location: not clearly provided.",f.service?`Service: ${f.service}`:"Service: not clearly provided.",f.duration?`Duration: ${f.duration}`:"Duration: not clearly provided.",f.start?`Start: ${f.start}`:"Start: not clearly provided.","","Urgency and timing",f.start?`Requested timing: ${f.start}`:"Requested timing needs confirmation.",f.duration?`Requested duration: ${f.duration}`:"Requested duration needs confirmation.",f.urgent?"Urgency: high based on the customer's wording.":"Urgency: not stated; do not assume.","","Contact details provided",f.phone?`Phone: ${f.phone}`:"Phone: not provided.",f.email?`Email: ${f.email}`:"Email: not provided.","","Missing information",missing.length?missing.map(x=>`- ${x}`).join("\n"):"No obvious essential detail is missing from the supplied enquiry.","","Recommended next action",f.availabilityRequested?"Check real availability for the requested period, then contact the customer with the result.":"Confirm the missing booking details, then contact the customer to progress the enquiry.","","Human handoff","A team member should take over for availability confirmation and any commercial or booking commitment."].join("\n");}

function extractCalendarFacts(message){const text=String(message||"").replace(/\s+/g," ").trim();const duration=firstMatch(/\b(?:arrange|schedule|book|set up)?\s*(?:a\s+)?(\d+\s*-?\s*(?:minute|minutes|hour|hours))\s+(?:meeting|appointment|call)\b/i,text)||firstMatch(/\b(?:for|lasting)\s+(\d+\s*(?:minutes?|hours?))\b/i,text);const attendee=firstMatch(/\b(?:with|for)\s+([A-Z][A-Za-z' -]{1,60}?)(?=\s+(?:next|this|on|at|in|to|for)\b|,|\.|$)/,text);const date=firstMatch(/\b((?:(?:next|this)\s+)?(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)|today|tomorrow|\d{1,2}(?:st|nd|rd|th)?\s+[A-Za-z]+(?:\s+\d{4})?)\b/i,text);const time=firstMatch(/\bat\s+(\d{1,2}(?::\d{2})?\s*(?:am|pm))\b/i,text);const email=firstMatch(/\b([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})\b/i,text);const location=firstMatch(/\bat\s+(?:our|the|a|an)\s+(.+?)(?=\s+(?:(?:next|this)\s+(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|week|month)|today|tomorrow)\b|\s+to\s+(?:discuss|review|meet|talk)\b|\.|,|$)/i,text);const purpose=firstMatch(/\bto\s+((?:discuss|review|talk about|meet about)\s+.+?)(?=\.|,\s*[A-Z][A-Za-z' -]+(?:'s)?\s+email\b|$)/i,text);return {duration,attendee,date,time,email,location,purpose};}
function calendarResponse(message){const f=extractCalendarFacts(message),missing=[];if(!f.date)missing.push("meeting date");if(!f.time)missing.push("meeting time");if(!f.duration)missing.push("meeting duration");if(!f.attendee)missing.push("attendee");if(!f.email)missing.push("attendee contact email");if(!f.location)missing.push("meeting location or method");return ["Appointment preparation",f.date?`Date: ${f.date}`:"Date: not provided.",f.time?`Time: ${f.time}`:"Time: not provided.",f.duration?`Duration: ${f.duration.replace(/\s*-\s*/,"-")}`:"Duration: not provided.",f.attendee?`Attendee: ${f.attendee}`:"Attendee: not clearly provided.",f.email?`Email: ${f.email}`:"Email: not provided.",f.location?`Location: ${f.location}`:"Location: not provided.",f.purpose?`Purpose: ${f.purpose}`:"Purpose: not clearly provided.","","Missing information",missing.length?missing.map(x=>`- ${x}`).join("\n"):"No obvious essential scheduling detail is missing from the request.","","Availability and conflicts","Availability has not been checked. Do not assume the requested time is free.","","Next action",missing.length?"Confirm the missing scheduling details, then check the live calendar before creating the appointment.":"Check the live calendar for availability and conflicts before creating or confirming the appointment.","","Status","Appointment prepared only. No calendar event has been created or confirmed."].join("\n");}

function extractBookingFacts(message){
  const text=String(message||"").replace(/\s+/g," ").trim();
  const customer=firstMatch(/\bfor\s+([A-Z][A-Za-z' -]{1,60}?)(?=\s+from\b|\.|,|$)/,text)||firstMatch(/(?:my name is|i am|i['’]m)\s+([A-Z][A-Za-z' -]{1,60}?)(?=\s+from\b|\.|,|$)/i,text)||firstMatch(/\b(?:customer|client)\s*(?:is|:)?\s*([A-Z][A-Za-z' -]{1,60}?)(?=\.|,|$)/i,text);
  const company=firstMatch(/\bfrom\s+(.+?)(?=\.|,\s*(?:she|he|they|i)\b|$)/i,text);
  const service=firstMatch(new RegExp(`(?:wants? to|needs? to|looking to|i need to)\\s+(?:hire|rent|book|buy|arrange|order)\\s+(.+?)(?=\\s+for\\s+${DURATION_QUANTITY}\\s*${DURATION_UNIT}\\b|\\s+starting\\b|\\s+from\\b|\\s+in\\s+[A-Z]|\\.|$)`,"i"),text)||firstMatch(new RegExp(`(?:prepare|create|make)\\s+(?:a\\s+)?booking.*?(?:for|to hire|to rent)\\s+(.+?)(?=\\s+for\\s+${DURATION_QUANTITY}\\s*${DURATION_UNIT}\\b|\\s+starting\\b|\\s+in\\s+[A-Z]|\\.|$)`,"i"),text);
  const duration=firstMatch(new RegExp(`\\bfor\\s+(${DURATION_QUANTITY}\\s*${DURATION_UNIT})\\b`,"i"),text);
  const start=firstMatch(/\bstarting\s+((?:(?:next|this)\s+)?(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)|today|tomorrow|\d{1,2}(?:st|nd|rd|th)?\s+[A-Za-z]+(?:\s+\d{4})?)/i,text);
  const rawLocation=firstMatch(new RegExp(`\\bin\\s+([A-Z][A-Za-z -]{2,40}?)(?=\\s+for\\s+${DURATION_QUANTITY}\\s*${DURATION_UNIT}\\b|\\.|,|\\s+(?:starting|from|next|this|today|tomorrow|her|his|their|my)\\b|$)`,"i"),text);
  const location=rawLocation.trim();
  const phone=firstMatch(/(?:phone(?: number)?|mobile|number)\s*(?:is|:)?\s*((?:\+44\s?\d|0\d)[\d\s-]{8,16})/i,text).replace(/[\s-]+/g,"");
  const email=firstMatch(/\b([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})\b/i,text);
  return {customer,company,service,duration,start,location,phone,email};
}
function bookingResponse(message){const f=extractBookingFacts(message),missing=[];if(!f.customer)missing.push("customer name");if(!f.service)missing.push("service or item required");if(!f.duration)missing.push("hire duration");if(!f.start)missing.push("start date");if(!f.location)missing.push("location");if(!f.phone&&!f.email)missing.push("customer contact details");return ["Booking preparation",f.customer?`Customer: ${f.customer}`:"Customer: not clearly provided.",f.company?`Business: ${f.company}`:"Business: not clearly provided.",f.service?`Service: ${f.service}`:"Service: not clearly provided.",f.duration?`Duration: ${f.duration}`:"Duration: not provided.",f.start?`Start: ${f.start}`:"Start: not provided.",f.location?`Location: ${f.location}`:"Location: not provided.",f.phone?`Phone: ${f.phone}`:"Phone: not provided.",f.email?`Email: ${f.email}`:"Email: not provided.","","Missing information",missing.length?missing.map(x=>`- ${x}`).join("\n"):"No obvious essential booking detail is missing from the supplied request.","","Availability","Availability has not been confirmed. Check live stock/service availability before making any commitment.","","Commercial controls","No price, deposit, payment term, delivery condition or policy has been invented or confirmed.","","Next action",missing.length?"Confirm the missing booking details, then check availability before progressing the booking.":"Check availability for the requested item/service and period, then contact the customer with the result.","","Status","Booking prepared only. No booking has been created, reserved, charged or confirmed."].join("\n");}

function extractLeadFacts(message){
  const text=String(message||"").replace(/\s+/g," ").trim();
  const customer=firstMatch(/(?:my name is|i am|i['’]m)\s+([A-Z][A-Za-z' -]{1,60}?)(?=\s+from\b|\.|,|$)/i,text);
  const company=firstMatch(/\bfrom\s+(.+?)(?=\.|,\s*(?:we|i)\b|$)/i,text);
  const phone=firstMatch(/(?:phone(?: number)?|mobile|number)\s*(?:is|:)?\s*((?:\+44\s?\d|0\d)[\d\s-]{8,16})/i,text).replace(/[\s-]+/g,"");
  const email=firstMatch(/\b([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})\b/i,text);
  const properties=firstMatch(/\b(?:manage|manages|managing)\s+(\d+)\s+(?:commercial\s+)?properties\b/i,text);
  const locations=firstMatch(/\bacross\s+(.+?)(?=\.|,\s*(?:we|our|i)\b|$)/i,text);
  const equipment=firstMatch(/\b(?:hire|need|require|use)\s+(.+?)\s+regularly\b/i,text)||firstMatch(/\b(?:expect to hire|looking to hire)\s+(.+?)(?=\s+regularly\b|\.|$)/i,text);
  const contractTiming=firstMatch(/\b(?:current\s+supplier\s+contract|supplier\s+contract|contract)\s+(?:ends|expires)\s+([^\.]+?)(?=\.|$)/i,text);
  const ongoing=/\bongoing\b|\bregularly\b|\brepeat\b|\brecurring\b/i.test(text);
  const newSupplier=/\bnew\s+(?:equipment\s+hire\s+)?supplier\b|\breplace\s+(?:our\s+)?supplier\b|\balternative\s+supplier\b/i.test(text);
  const salesContact=/\bsales\s+team\b|\bsales\s+contact\b|\bcontact me\b|\bcall me\b/i.test(text);
  const nearTerm=/\bnext\s+(?:week|month)\b|\bthis\s+(?:week|month)\b|\burgent\b|\basap\b/i.test(text);
  return {customer,company,phone,email,properties,locations,equipment,contractTiming,ongoing,newSupplier,salesContact,nearTerm};
}
function leadResponse(message){
  const f=extractLeadFacts(message);const missing=[];
  if(!f.customer)missing.push("contact name");if(!f.company)missing.push("business name");if(!f.phone&&!f.email)missing.push("contact details");
  const intent=(f.newSupplier||f.ongoing||f.contractTiming)?"Strong buying intent based on stated supplier change, recurring demand or contract timing.":"Buying intent is present but needs further qualification.";
  const priority=(f.nearTerm||f.contractTiming)?"High priority for sales follow-up because a near-term timing signal was provided.":"Normal priority until timing is clarified.";
  return ["Lead analysis",f.customer?`Contact: ${f.customer}`:"Contact: not clearly provided.",f.company?`Business: ${f.company}`:"Business: not clearly provided.",f.properties?`Portfolio: ${f.properties} commercial properties`:"Portfolio size: not clearly provided.",f.locations?`Locations: ${f.locations}`:"Locations: not clearly provided.",f.equipment?`Requirement: ${f.equipment}`:"Requirement: not clearly provided.",f.ongoing?"Opportunity type: ongoing / repeat requirement":"Opportunity type: repeat requirement not clearly established.",f.contractTiming?`Supplier timing: contract ${f.contractTiming}`:"Supplier timing: not clearly provided.",f.phone?`Phone: ${f.phone}`:"Phone: not provided.",f.email?`Email: ${f.email}`:"Email: not provided.","","Buying intent",intent,"","Priority",priority,"","Missing information",missing.length?missing.map(x=>`- ${x}`).join("\n"):"No obvious essential lead identity or contact detail is missing.","","Recommended sales action",f.salesContact?"Sales team should contact the prospect using the supplied details, confirm requirements, timing, buying process and next commercial step.":"Qualify requirements, timing, buying process and preferred follow-up method before progressing.","","Commercial safeguards","Do not invent budget, revenue, pricing, probability, contract value, decision-maker status or purchase authority unless the prospect supplied it."].join("\n");
}

function cleanReply(reply){const v=String(reply||"").replace(/\\n/g,"\n").replace(/\\r/g,"").replace(/\\{2,}/g,"").trim();return INTERNAL_MARKERS.test(v)?"":v;}
async function runAI(env,tool,message){if(tool==="receptionist")return{ok:true,reply:receptionistResponse(message),structured:true,degraded:false};if(tool==="calendar")return{ok:true,reply:calendarResponse(message),structured:true,degraded:false};if(tool==="booking")return{ok:true,reply:bookingResponse(message),structured:true,degraded:false};if(tool==="leads")return{ok:true,reply:leadResponse(message),structured:true,degraded:false};if(!env.AI||typeof env.AI.run!=="function")return{ok:false,error:"Workers AI binding is not available."};const system=TOOL_PROMPTS[tool]||TOOL_PROMPTS.ask;try{const result=await env.AI.run(AI_MODEL,{messages:[{role:"system",content:system},{role:"user",content:message}],max_completion_tokens:700,temperature:0.1,top_p:0.8,repetition_penalty:1.12,frequency_penalty:0.35});const reply=cleanReply(extractReply(result));if(reply)return{ok:true,reply,degraded:false};}catch(error){console.error("Workers AI inference failed",error);}return{ok:false,error:"The AI model did not return a safe usable response."};}

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET"){const aiConfigured=Boolean(env.AI&&typeof env.AI.run==="function"),dbConfigured=Boolean(env.DB);return json({ok:aiConfigured&&dbConfigured,service:"zorvian-platform",aiConfigured,dbConfigured,aiModel:AI_MODEL,time:new Date().toISOString()},aiConfigured&&dbConfigured?200:503);}if(url.pathname.startsWith("/api/ai/")&&request.method==="POST"){const user=await getUser(request,env);if(!user)return json({error:"unauthorized"},401);const requestedTool=url.pathname.slice("/api/ai/".length).replace(/\/$/,"");const tool=requestedTool==="enquiry"?"receptionist":requestedTool;if(!TOOL_PROMPTS[tool])return json({error:"unknown_ai_tool"},404);let body;try{body=await request.json();}catch{return json({error:"invalid_json"},400);}const message=String(body.message||body.command||"").trim().slice(0,8000);if(!message)return json({error:"message_required"},400);const result=await runAI(env,tool,message);if(!result.ok)return json({ok:false,tool,error:result.error},503);return json({ok:true,tool,model:AI_MODEL,reply:result.reply,degraded:Boolean(result.degraded),structured:Boolean(result.structured)});}return legacyWorker.fetch(request,env,ctx);}};