const JSON_HEADERS={"content-type":"application/json; charset=UTF-8","cache-control":"no-store"};
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
const PROVIDERS=new Set(['twilio','telnyx','vonage']);

function cookie(request,name){const h=request.headers.get('Cookie')||'';const m=h.match(new RegExp(`(?:^|; )${name}=([^;]+)`));return m?m[1]:null;}
async function sessionUser(request,env){const id=cookie(request,'zorvian_session');if(!id||!env.DB)return null;return env.DB.prepare(`SELECT u.id,u.name,u.email,u.role,u.tenant_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?`).bind(id,now()).first();}
function serviceUser(request,env){const a=request.headers.get('Authorization')||'';if(!env.CRM_ADMIN_TOKEN||!a.startsWith('Bearer '))return null;const t=a.slice(7).trim();if(t!==env.CRM_ADMIN_TOKEN)return null;return{id:'receptionist-service',name:'Caelomere Receptionist Service',role:'admin',tenant_id:env.CRM_ADMIN_TENANT||'zorvian',service:true};}
async function authUser(request,env){return serviceUser(request,env)||await sessionUser(request,env);}
const tenant=u=>u.tenant_id||'zorvian';
function phone(v){return String(v||'').trim().replace(/[^+\d]/g,'').replace(/^00/,'+');}
async function sha256(v){const bytes=new TextEncoder().encode(String(v||''));const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}

async function schema(env){await env.DB.batch([
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS receptionist_provider_configs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,provider TEXT NOT NULL,inbound_number TEXT NOT NULL,webhook_secret_hash TEXT,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,provider,inbound_number))`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS receptionist_sessions(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,channel TEXT NOT NULL,provider TEXT,provider_call_id TEXT,caller_phone TEXT,called_phone TEXT,contact_id TEXT,status TEXT NOT NULL DEFAULT 'active',started_at TEXT NOT NULL,ended_at TEXT,last_intent TEXT,last_summary TEXT)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS receptionist_turns(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,tenant_id TEXT NOT NULL,speaker TEXT NOT NULL,text TEXT NOT NULL,intent TEXT,urgency TEXT,actions_json TEXT,created_at TEXT NOT NULL)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS receptionist_events(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,session_id TEXT,provider TEXT,event_type TEXT NOT NULL,payload_json TEXT,created_at TEXT NOT NULL)`),
 env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_receptionist_provider_number ON receptionist_provider_configs(provider,inbound_number,active)`),
 env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_receptionist_sessions_tenant ON receptionist_sessions(tenant_id,started_at)`),
 env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_receptionist_turns_session ON receptionist_turns(session_id,created_at)`)
]);}

async function findContact(env,t,number){const n=phone(number);if(!n)return null;const r=await env.DB.prepare(`SELECT * FROM crm_contacts WHERE tenant_id=? AND REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(phone,' ',''),'-',''),'(',''),')',''),'.','') IN (?,?) ORDER BY updated_at DESC LIMIT 1`).bind(t,n,n.replace(/^\+44/,'0')).first();return r||null;}
async function contactContext(env,t,contact){if(!contact)return {contact:null,activity:[],tasks:[],leads:[]};const [activity,tasks,leads]=await Promise.all([
 env.DB.prepare(`SELECT action,detail,created_at FROM crm_activity WHERE tenant_id=? AND entity_id=? ORDER BY created_at DESC LIMIT 12`).bind(t,contact.id).all(),
 env.DB.prepare(`SELECT title,status,priority,due_at,notes FROM crm_tasks WHERE tenant_id=? AND contact_id=? ORDER BY updated_at DESC LIMIT 12`).bind(t,contact.id).all().catch(()=>({results:[]})),
 env.DB.prepare(`SELECT name,company,status,value,next_action,follow_up_at,notes FROM crm_leads WHERE tenant_id=? AND contact_id=? ORDER BY updated_at DESC LIMIT 12`).bind(t,contact.id).all().catch(()=>({results:[]}))
]);return {contact,activity:activity.results||[],tasks:tasks.results||[],leads:leads.results||[]};}

function parseAI(text){const cleaned=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/```$/,'').trim();try{return JSON.parse(cleaned);}catch{return {reply:cleaned,intent:'general_enquiry',urgency:'normal',actions:[],summary:cleaned.slice(0,500)};}}
async function receptionistAI(env,ctx,input){if(!env.AI||typeof env.AI.run!=='function')throw new Error('ai_unavailable');const system=`You are the Caelomere AI Receptionist powered by Caelomere Celestial Core. Be warm, concise and commercially useful. Use only supplied CRM facts. Never invent price, availability, bookings, payments, policies or completed actions. Identify caller intent and urgency. Return VALID JSON ONLY with keys reply, intent, urgency, actions, summary. actions must be an array of proposed structured objects chosen from: crm_note, create_task, draft_email, draft_sms, request_human, booking_request, lead_update. Never claim an external action happened; proposals require approval unless a connected integration confirms execution.`;
 const prompt=`CHANNEL: ${ctx.channel}\nCALLER PHONE: ${ctx.caller_phone||''}\nCONTACT/CRM CONTEXT:\n${JSON.stringify(ctx.crm)}\n\nCURRENT USER SPEECH/TEXT:\n${input}`;
 const out=await env.AI.run('@cf/zai-org/glm-4.7-flash',{messages:[{role:'system',content:system},{role:'user',content:prompt}],max_completion_tokens:1100,temperature:.12,top_p:.82});return parseAI(out?.response||out?.result?.response||out?.output_text||out?.text||'');}

async function createSession(env,t,{channel='website',provider=null,provider_call_id=null,caller_phone='',called_phone='',contact_id=null}={}){const id=uid(),ts=now();await env.DB.prepare(`INSERT INTO receptionist_sessions(id,tenant_id,channel,provider,provider_call_id,caller_phone,called_phone,contact_id,status,started_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,t,channel,provider,provider_call_id,phone(caller_phone),phone(called_phone),contact_id,'active',ts).run();return id;}
async function logEvent(env,t,sessionId,provider,eventType,payload){await env.DB.prepare(`INSERT INTO receptionist_events(id,tenant_id,session_id,provider,event_type,payload_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(uid(),t,sessionId||null,provider||null,eventType,JSON.stringify(payload||{}).slice(0,24000),now()).run();}

function normaliseWebhook(provider,body,headers){if(provider==='twilio'){return {event:body.CallStatus||body.SpeechResult?'speech':'call',call_id:body.CallSid||'',from:body.From||'',to:body.To||'',speech:body.SpeechResult||'',status:body.CallStatus||''};}
 if(provider==='telnyx'){const d=body.data||{},p=d.payload||{};return {event:d.event_type||'call',call_id:p.call_control_id||p.call_leg_id||'',from:p.from||p.from_number||'',to:p.to||p.to_number||'',speech:p.speech?.text||p.transcript||'',status:p.state||''};}
 const c=body.conversation_uuid||body.uuid||body.call_uuid||'';return {event:body.status||body.type||'call',call_id:c,from:body.from||body.from_number||'',to:body.to||body.to_number||'',speech:body.speech?.results?.[0]?.text||body.transcript||'',status:body.status||''};}
async function bodyData(request){const ct=request.headers.get('content-type')||'';if(ct.includes('application/x-www-form-urlencoded'))return Object.fromEntries(new URLSearchParams(await request.text()));try{return await request.json();}catch{return {};}}

async function providerConfigForCall(env,provider,to){return env.DB.prepare(`SELECT * FROM receptionist_provider_configs WHERE provider=? AND inbound_number=? AND active=1 LIMIT 1`).bind(provider,phone(to)).first();}
async function verifyWebhook(request,cfg){if(!cfg?.webhook_secret_hash)return false;const supplied=request.headers.get('x-caelomere-webhook-secret')||new URL(request.url).searchParams.get('secret')||'';if(!supplied)return false;return (await sha256(supplied))===cfg.webhook_secret_hash;}

export async function handleReceptionist(request,env){const url=new URL(request.url),p=url.pathname;if(!p.startsWith('/api/receptionist'))return null;if(!env.DB)return json({error:'database_unavailable'},503);await schema(env);
 if(p==='/api/receptionist/health'&&request.method==='GET')return json({ok:true,service:'Caelomere AI Receptionist',core:'Caelomere Celestial Core',ai_ready:Boolean(env.AI&&typeof env.AI.run==='function'),providers:['twilio','telnyx','vonage'],capabilities:['caller_lookup','crm_context','website_conversation','dictation','transcript','action_proposals','provider_webhooks']});
 if(p.startsWith('/api/receptionist/webhooks/')){const provider=p.split('/').pop();if(!PROVIDERS.has(provider))return json({error:'unknown_provider'},404);if(request.method!=='POST')return json({error:'method_not_allowed'},405);const raw=await bodyData(request);const evt=normaliseWebhook(provider,raw,request.headers);const cfg=await providerConfigForCall(env,provider,evt.to);if(!cfg)return json({error:'inbound_number_not_configured'},404);if(!(await verifyWebhook(request,cfg)))return json({error:'invalid_webhook_secret'},401);const t=cfg.tenant_id;let s=await env.DB.prepare(`SELECT * FROM receptionist_sessions WHERE tenant_id=? AND provider=? AND provider_call_id=? ORDER BY started_at DESC LIMIT 1`).bind(t,provider,evt.call_id).first();if(!s){const contact=await findContact(env,t,evt.from);const id=await createSession(env,t,{channel:'phone',provider,provider_call_id:evt.call_id,caller_phone:evt.from,called_phone:evt.to,contact_id:contact?.id||null});s=await env.DB.prepare(`SELECT * FROM receptionist_sessions WHERE id=?`).bind(id).first();}
 await logEvent(env,t,s.id,provider,evt.event,raw);
 if(evt.speech){const contact=s.contact_id?await env.DB.prepare(`SELECT * FROM crm_contacts WHERE id=? AND tenant_id=?`).bind(s.contact_id,t).first():await findContact(env,t,evt.from);const crm=await contactContext(env,t,contact);await env.DB.prepare(`INSERT INTO receptionist_turns(id,session_id,tenant_id,speaker,text,created_at) VALUES(?,?,?,?,?,?)`).bind(uid(),s.id,t,'caller',evt.speech,now()).run();const ai=await receptionistAI(env,{channel:'phone',caller_phone:evt.from,crm},evt.speech);await env.DB.prepare(`INSERT INTO receptionist_turns(id,session_id,tenant_id,speaker,text,intent,urgency,actions_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(uid(),s.id,t,'receptionist',ai.reply||'',ai.intent||'',ai.urgency||'',JSON.stringify(ai.actions||[]),now()).run();await env.DB.prepare(`UPDATE receptionist_sessions SET last_intent=?,last_summary=? WHERE id=?`).bind(ai.intent||'',ai.summary||'',s.id).run();return json({ok:true,session_id:s.id,caller_recognised:Boolean(contact),contact:contact?{id:contact.id,name:contact.name,company:contact.company}:null,reply:ai.reply,intent:ai.intent,urgency:ai.urgency,actions:ai.actions||[],provider_response_required:true});}
 return json({ok:true,session_id:s.id,caller_recognised:Boolean(s.contact_id),event:evt.event,status:evt.status||''});}

 const u=await authUser(request,env);if(!u)return json({error:'unauthorized'},401);const t=tenant(u);
 if(p==='/api/receptionist/providers'&&request.method==='GET'){const r=await env.DB.prepare(`SELECT provider,inbound_number,active,created_at,updated_at FROM receptionist_provider_configs WHERE tenant_id=? ORDER BY provider,inbound_number`).bind(t).all();return json({ok:true,items:r.results||[],supported:['twilio','telnyx','vonage']});}
 if(p==='/api/receptionist/providers'&&request.method==='POST'){let b={};try{b=await request.json();}catch{return json({error:'invalid_json'},400)}const provider=String(b.provider||'').toLowerCase(),number=phone(b.inbound_number),secret=String(b.webhook_secret||'');if(!PROVIDERS.has(provider)||!number||secret.length<12)return json({error:'provider_number_and_webhook_secret_required'},400);const ts=now(),id=uid(),hash=await sha256(secret);await env.DB.prepare(`INSERT INTO receptionist_provider_configs(id,tenant_id,provider,inbound_number,webhook_secret_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(tenant_id,provider,inbound_number) DO UPDATE SET webhook_secret_hash=excluded.webhook_secret_hash,active=1,updated_at=excluded.updated_at`).bind(id,t,provider,number,hash,1,ts,ts).run();return json({ok:true,provider,inbound_number:number,webhook_path:`/api/receptionist/webhooks/${provider}`},201);}
 if(p==='/api/receptionist/caller-lookup'&&request.method==='POST'){let b={};try{b=await request.json();}catch{return json({error:'invalid_json'},400)}const contact=await findContact(env,t,b.phone);const crm=await contactContext(env,t,contact);return json({ok:true,matched:Boolean(contact),crm});}
 if(p==='/api/receptionist/sessions'&&request.method==='POST'){let b={};try{b=await request.json();}catch{return json({error:'invalid_json'},400)}const caller=phone(b.caller_phone),contact=caller?await findContact(env,t,caller):null;const id=await createSession(env,t,{channel:String(b.channel||'website'),provider:b.provider||null,caller_phone:caller,called_phone:b.called_phone||'',contact_id:contact?.id||null});return json({ok:true,id,caller_recognised:Boolean(contact),contact:contact?{id:contact.id,name:contact.name,company:contact.company}:null},201);}
 const m=p.match(/^\/api\/receptionist\/sessions\/([^/]+)\/message$/);if(m&&request.method==='POST'){let b={};try{b=await request.json();}catch{return json({error:'invalid_json'},400)}const text=String(b.text||'').trim();if(!text)return json({error:'text_required'},400);const s=await env.DB.prepare(`SELECT * FROM receptionist_sessions WHERE id=? AND tenant_id=?`).bind(m[1],t).first();if(!s)return json({error:'session_not_found'},404);const contact=s.contact_id?await env.DB.prepare(`SELECT * FROM crm_contacts WHERE id=? AND tenant_id=?`).bind(s.contact_id,t).first():null;const crm=await contactContext(env,t,contact);await env.DB.prepare(`INSERT INTO receptionist_turns(id,session_id,tenant_id,speaker,text,created_at) VALUES(?,?,?,?,?,?)`).bind(uid(),s.id,t,'user',text,now()).run();let ai;try{ai=await receptionistAI(env,{channel:s.channel,caller_phone:s.caller_phone,crm},text);}catch(e){return json({error:String(e.message||'ai_failed')},503)}await env.DB.prepare(`INSERT INTO receptionist_turns(id,session_id,tenant_id,speaker,text,intent,urgency,actions_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(uid(),s.id,t,'receptionist',ai.reply||'',ai.intent||'',ai.urgency||'',JSON.stringify(ai.actions||[]),now()).run();await env.DB.prepare(`UPDATE receptionist_sessions SET last_intent=?,last_summary=? WHERE id=?`).bind(ai.intent||'',ai.summary||'',s.id).run();if(contact){await env.DB.prepare(`INSERT INTO crm_activity(id,tenant_id,entity_type,entity_id,action,detail,created_at) VALUES(?,?,?,?,?,?,?)`).bind(uid(),t,'contact',contact.id,'receptionist_interaction',ai.summary||text.slice(0,500),now()).run();}return json({ok:true,session_id:s.id,caller_recognised:Boolean(contact),contact:contact?{id:contact.id,name:contact.name,company:contact.company}:null,reply:ai.reply,intent:ai.intent,urgency:ai.urgency,actions:ai.actions||[],external_actions_executed:false});}
 const tm=p.match(/^\/api\/receptionist\/sessions\/([^/]+)\/transcript$/);if(tm&&request.method==='GET'){const s=await env.DB.prepare(`SELECT * FROM receptionist_sessions WHERE id=? AND tenant_id=?`).bind(tm[1],t).first();if(!s)return json({error:'session_not_found'},404);const r=await env.DB.prepare(`SELECT speaker,text,intent,urgency,actions_json,created_at FROM receptionist_turns WHERE session_id=? AND tenant_id=? ORDER BY created_at`).bind(s.id,t).all();return json({ok:true,session:s,turns:(r.results||[]).map(x=>({...x,actions:x.actions_json?JSON.parse(x.actions_json):[]}))});}
 return json({error:'not_found'},404);
}
