const J={"content-type":"application/json;charset=UTF-8"};const uid=()=>crypto.randomUUID();const now=()=>new Date().toISOString();
const json=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{...J,...h}});
const cookie=(n,v,age=604800)=>`${n}=${v}; Path=/; Max-Age=${age}; HttpOnly; Secure; SameSite=Lax`;
const getCookie=(r,n)=>{const m=(r.headers.get('Cookie')||'').match(new RegExp(`(?:^|; )${n}=([^;]+)`));return m&&m[1]};
async function hash(p,s=crypto.randomUUID()){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(s),iterations:10000,hash:'SHA-256'},k,256);return s+'$'+btoa(String.fromCharCode(...new Uint8Array(b)))}
async function verify(p,x){const [s]=x.split('$');return await hash(p,s)===x}
async function me(r,e){const sid=getCookie(r,'zorvian_session');if(!sid)return null;return await e.DB.prepare(`SELECT s.id,s.expires_at,u.id user_id,u.name,u.email,u.role,u.tenant_id,t.name tenant_name,t.slug tenant_slug,t.website_url FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN tenants t ON t.id=u.tenant_id WHERE s.id=? AND s.expires_at>?`).bind(sid,now()).first()}
async function audit(e,u,a,d={}){await e.DB.prepare('INSERT INTO audit_logs(id,tenant_id,user_id,action,details_json) VALUES(?,?,?,?,?)').bind(uid(),u?.tenant_id||null,u?.user_id||null,a,JSON.stringify(d)).run()}
export default {async fetch(r,e){const u=new URL(r.url);try{
if(u.pathname==='/api/health')return json({ok:true,service:'zorvian-platform',time:now()});
if(u.pathname==='/api/auth/register'&&r.method==='POST'){const b=await r.json(),name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),pass=String(b.password||'');if(!name||!email||pass.length<10)return json({error:'Name, email and a password of at least 10 characters are required.'},400);if(await e.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'Account already exists.'},409);const tid=uid(),zid=uid(),base=(b.business||name).toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,45)||tid.slice(0,8);let slug=base;if(await e.DB.prepare('SELECT id FROM tenants WHERE slug=?').bind(slug).first())slug=base+'-'+tid.slice(0,6);await e.DB.batch([e.DB.prepare('INSERT INTO tenants(id,name,slug,website_url) VALUES(?,?,?,?)').bind(tid,b.business||name,slug,b.website_url||null),e.DB.prepare('INSERT INTO users(id,tenant_id,name,email,password_hash,role) VALUES(?,?,?,?,?,?)').bind(zid,tid,name,email,await hash(pass),'client')]);const sid=uid();await e.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(sid,zid,new Date(Date.now()+604800000).toISOString()).run();return json({ok:true},{headers:{...J,'Set-Cookie':cookie('zorvian_session',sid)}})}
if(u.pathname==='/api/auth/login'&&r.method==='POST'){const b=await r.json(),email=String(b.email||'').trim().toLowerCase(),pass=String(b.password||''),x=await e.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!x||!(await verify(pass,x.password_hash)))return json({error:'Invalid email or password.'},401);const sid=uid();await e.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(sid,x.id,new Date(Date.now()+604800000).toISOString()).run();return json({ok:true,user:{name:x.name,email:x.email,role:x.role}},{headers:{...J,'Set-Cookie':cookie('zorvian_session',sid)}})}
if(u.pathname==='/api/auth/logout'&&r.method==='POST'){const sid=getCookie(r,'zorvian_session');if(sid)await e.DB.prepare('DELETE FROM sessions WHERE id=?').bind(sid).run();return json({ok:true},200,{'Set-Cookie':cookie('zorvian_session','',0)})
const user=await me(r,e);if(u.pathname==='/api/me')return user?json({authenticated:true,user:{id:user.user_id,name:user.name,email:user.email,role:user.role},tenant:{id:user.tenant_id,name:user.tenant_name,slug:user.tenant_slug,website_url:user.website_url}}):json({authenticated:false});
if(!user)return json({error:'unauthorized'},401);
if(u.pathname==='/api/leads'&&r.method==='GET'){const q=await e.DB.prepare('SELECT id,name,company,email,phone,source,requirement,status,priority,created_at FROM leads WHERE tenant_id=? ORDER BY datetime(created_at) DESC LIMIT 100').bind(user.tenant_id).all();return json({leads:q.results})}
if(u.pathname==='/api/leads'&&r.method==='POST'){const b=await r.json(),lid=uid(),priority=b.priority||(/urgent|today|asap|emergency/i.test(b.requirement||'')?'urgent':'normal');await e.DB.prepare('INSERT INTO leads(id,tenant_id,name,company,email,phone,source,requirement,priority,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(lid,user.tenant_id,b.name||null,b.company||null,b.email||null,b.phone||null,b.source||'website',b.requirement||'',priority,JSON.stringify(b.metadata||{})).run();await audit(e,user,'lead.created',{lid});return json({ok:true,id:lid,priority},201)}
if(u.pathname==='/api/ai/enquiry'&&r.method==='POST'){const b=await r.json(),m=String(b.message||'').slice(0,5000);if(!m)return json({error:'message_required'},400);let reply='Please tell me what needs doing, where it starts, where it needs to go, and when it needs to happen.';if(e.AI)try{const x=await e.AI.run('@cf/zai-org/glm-4.7-flash',{messages:[{role:'system',content:'You are Zorvian, a concise business AI assistant. Qualify enquiries. Never invent prices or availability. Ask for missing details and hand off to a human when needed.'},{role:'user',content:m}]});reply=x?.response||reply}catch(_){}return json({reply})}
if(u.pathname==='/api/ai/command'&&r.method==='POST'){const b=await r.json(),m=String(b.command||'').slice(0,3000);let reply='Action received. I will prepare the requested change and keep production actions behind approval.';if(e.AI)try{const x=await e.AI.run('@cf/zai-org/glm-4.7-flash',{messages:[{role:'system',content:'You are Zorvian business control AI. Interpret commands for website content, leads, campaigns, follow-ups and reporting. Never claim an action was published or sent unless an integration executed it. Return a short action plan and required system.'},{role:'user',content:m}]});reply=x?.response||reply}catch(_){}await audit(e,user,'ai.command',{command:m});return json({reply})}
return e.ASSETS.fetch(r);
} catch(err) {
  console.error(err);
  return json({error:'server_error'},500);
}
}};
