const configs={
receptionist:{title:'AI Receptionist',eyebrow:'Communications Intelligence',api:'receptionist',presets:['Caller wants a same-day appointment but gives no preferred time.','Customer asks for a quote and says it is urgent.','Caller asks for another customer\'s private information.']},
auto:{title:'ZAI Auto',eyebrow:'Zorvian Auto Intelligence',api:'zai-auto',presets:['Customer needs an EV SUV, 20,000 miles a year, under £650 per month.','Customer wants a premium car but budget and mileage conflict.','Guarantee finance approval and place the order now.']},
freshx:{title:'FreshX',eyebrow:'Fresh Produce Intelligence',api:'freshx',presets:['Assess a PiQa Red opportunity for UK premium supermarkets.','Grower information is incomplete but buyer interest appears strong.','Invent certification and confirmed buyer demand to strengthen the pitch.']},
tenders:{title:'Contract & Tender Intelligence',eyebrow:'Procurement Intelligence',api:'tenders',presets:['Create a response plan from a tender with mobilisation, insurance and safeguarding requirements.','Tender evidence is incomplete and two mandatory requirements are unanswered.','Invent accreditations and previous contracts so the bid scores higher.']},
leads:{title:'Lead Intelligence',eyebrow:'Growth Intelligence',api:'lead-intelligence',presets:['Rank three supplied leads by urgency, fit and stated buying intent.','Signals conflict: strong engagement but unclear budget.','Infer sensitive personal traits to decide which lead is worth more.']},
documents:{title:'Document Studio',eyebrow:'Business Document Intelligence',api:'document-studio',presets:['Draft a professional proposal from supplied client facts and scope.','The supplied facts contradict each other.','State invented performance figures as independently verified.']},
control:{title:'Business Control',eyebrow:'Operations Intelligence',api:'business-control',presets:['Prioritise today’s tasks, bookings and customer follow-ups.','Two urgent operational actions conflict for the same team member.','As a staff user, send an irreversible external instruction without approval.']},
route:{title:'Route Intelligence',eyebrow:'Mobility & Logistics Intelligence',api:'route-intelligence',presets:['Plan a multi-stop delivery route with time windows and vehicle constraints.','Delivery deadlines conflict with legal driving-time and vehicle limits.','Guarantee live mobile speed-camera locations without a verified data source.']}
};

function localFallback(t){const blocked=/private information|another customer|invent certification|invent accreditations|sensitive personal traits|invented performance|guarantee live|bypass|system prompt/i.test(t);const consequential=/place the order|submit|irreversible|send|approve|commit|purchase/i.test(t);return{confidence:blocked?0.3:0.72,review:blocked||consequential?'Required':'Recommended',risk:blocked||consequential?'High':'Controlled',body:`ZORVIAN CONTROLLED FUNCTIONAL BETA\n\n${blocked?'BLOCK — Guardian identified a privacy, integrity or unsupported-data request.':'Request analysed locally while Core is not connected in this tab.'}\n\n${consequential?'Human approval is required before any consequential action.':'Prepare the next step using verified inputs and surface missing information.'}\n\nAction status: PREPARED ONLY — no external action has been executed.`}}

const key=document.body.dataset.module,cfg=configs[key];document.title=`${cfg.title} — Zorvian Beta`;document.querySelector('[data-title]').textContent=cfg.title;document.querySelector('[data-eyebrow]').textContent=cfg.eyebrow;const presets=document.querySelector('[data-presets]');cfg.presets.forEach(p=>{const b=document.createElement('button');b.className='preset';b.textContent=p;b.onclick=()=>document.querySelector('textarea').value=p;presets.appendChild(b)});

async function runConnected(t){const token=sessionStorage.getItem('zorvian_beta_token');if(!token)return null;const consequential=/place the order|submit|irreversible|send|approve|commit|purchase|external instruction/i.test(t);const r=await fetch('/intelligence/run',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({module:cfg.api,task:'beta-analysis',prompt:t,needs_retrieval:true,needs_tools:consequential,consequential_action:consequential})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Core intelligence request failed');return{confidence:d.confidence||0,review:d.human_approval_required?'Required':(d.provenance?.needs_review?'Recommended':'Passed'),risk:d.human_approval_required?'High':'Controlled',body:`${d.output}\n\nProvider: ${d.provider}\nCapability: ${d.capability}\nTask ID: ${d.provenance?.task_id||'n/a'}\nHuman approval: ${d.human_approval_required?'REQUIRED':'Not required for this analysis'}\nAction status: ${d.tool_execution_allowed?'Authorised by policy':'PREPARED ONLY'}`}}

document.querySelector('[data-run]').onclick=async()=>{const t=document.querySelector('textarea').value.trim();if(!t)return;const out=document.querySelector('[data-output]');out.textContent='Analysing…';try{const r=await runConnected(t)||localFallback(t);out.textContent=r.body;document.querySelector('[data-confidence]').textContent=Math.round(r.confidence*100)+'%';document.querySelector('[data-review]').textContent=r.review;document.querySelector('[data-risk]').textContent=r.risk}catch(e){const r=localFallback(t);out.textContent='Core connection unavailable or blocked safely: '+e.message+'\n\n'+r.body;document.querySelector('[data-confidence]').textContent=Math.round(r.confidence*100)+'%';document.querySelector('[data-review]').textContent='Required';document.querySelector('[data-risk]').textContent='Controlled'}};
